### ISSUE TITLE
Open for testing?

### ISSUE THREAD

**Issue by damntourists** [jjasghar/charts#2]
I'm curious if this is in a state where I could try running this on my digitalocean k8s cluster? I'm very interested in running an instance of Huginn and this seems like it could be what I'm looking for. I saw on your pull request at https://github.com/huginn/huginn/pull/2733 and saw that it's still open so I was wondering if I should hold off until that PR is closed?

I'm a bit new to using helm/k8s, so I'm unsure how to install this. Would I need to host my own helm repo to get this functioning, or could I edit the configs and install it from disc?

Also, apologies for opening an issue, I don't have a bug to report. I was unsure how to contact those involved in putting this together.

Thanks for your time!

**Comment by jjasghar** [comment]
Hi!

So yes, right now it _works_ the best we can. We actually streamed us getting it working over a couple of weeks: https://www.youtube.com/watch?v=0cSdmBmIyVo and https://www.youtube.com/c/JJAsghar/videos for the full list. Look for anything with Huginn in it...

The https://github.com/jjasghar/charts/blob/master/charts/huginn/values.yaml is a sane default, and the docs (sparse yes) are accurate too.

Hopefully, that'll at least get you started, and if you have any ideas or thoughts PRs are very welcome.

**Comment by damntourists** [comment]
One question before I begin: is the data persisted or would I lose all database entries should I need to redeploy?

**Comment by jjasghar** [comment]
I'm 95% sure if you change this to true, it will keep the data persisted per deployments: https://github.com/jjasghar/charts/blob/master/charts/huginn/values.yaml#L27-L28

**Comment by damntourists** [comment]
Okay, I was able to get it deployed successfully, however, noticed that some of the email settings didn't get applied. They're present in the values.yaml but after install, i see the k8s config that was created has the `REQUIRE_CONFIRMED_EMAIL` and `ALLOW_UNCONFIRMED_ACCESS_FOR` settings commented out. 
```
            # - name: REQUIRE_CONFIRMED_EMAIL                                                                                       
            #   value: "true"                                                                                                       
            # - name: ALLOW_UNCONFIRMED_ACCESS_FOR                                                                                  
            #   value: "1.days"                                                                                                     
          imagePullPolicy: IfNotPresent                                                                                             
          ports:                                                                                                                    
            - name: http                                                                                                            
              containerPort: 3000                                                                                                   
```
